name: Node.js Unitests CI Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./0x06-unittests_in_js

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 12
        cache: 'npm'

    - name: Run npm clean install
      run: npm ci

    - name: Run npm build if present
      run: npm run build --if-present
    
    - name: Run unit and integration tests
      run: npm run test *.test.js
